name: Build Angular App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd angular-app
          npm ci
      - name: Build
        run: |
          cd angular-app
          npm run build:web
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: angular-app/dist/goatfarm-angular
